
version: '2'
services:
  api_agenda_app:
    image: node:12-alpine
    container_name: api_agenda_app
    build: ./
    command: "/bin/sh -c 'cd /app && npm i && npm run start'"
    volumes:
      - ./:/app
    ports:
      - "4001:4001"
    networks:
      api_agenda_net:
        ipv4_address: 172.38.0.2
    environment:
      NAME: LOCAL
      NODE_ENV: development
      MONGO_IP: 172.38.0.4
      MONGO_PORT: 27017
      MONGO_USER: 'admin'
      MONGO_PASSWORD: 'root123'
      MONGO_DB_NAME: 'schedule_main'
      WEATHER_API_URI: https://api.hgbrasil.com/weather
      WEATHER_API_KEY: '7a4eddad'
  api_agenda_database:
    image: mongo:4.0
    container_name: api_agenda_database
    ports:
      - "27017:27017"
    networks:
      api_agenda_net:
        ipv4_address: 172.38.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: schedule_main
    volumes:
      - ./scripts/mongo-init-script.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --smallfiles
networks:
  api_agenda_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.38.0.0/16
          gateway: 172.38.0.1
volumes:
  appdata:
    driver: local